Second rules update in v1 branch, update names, update `write_standard_name_table.py` to allow for subsections
ESCOMP/ESMStandardNames pull request #87
Opened 2024-12-13 03:41 UTC by mkavulich

This is the second round of proposed rules changes based on our ongoing discussion to make both rules and names as consistent as possible. Major updates include:

### Standard Names
 - New "base_names" section, with subsections
 - Convert instances of "surface_X" to "X_at_surface"
 - Convert some instances of "air_X" or "X_of_air"
 - Explicitly state what mass mixing ratios are with respect to in long_name
 - Convert "mixing_ratio" to "water_vapor_mixing_ratio_wrt_moist_air"
 - Convert "surface_albedo" to simply "albedo", "surface_roughness_length" to simply "roughness_length"

### Rules
 - Update construction template to include [non-instant time] and [non-current time], swap [at level] and [in medium]
 - More detailed description of transformations and how they can work on multiple base names
 - Add a few more transformations

### `write_standard_name_table.py`
 - Updated to allow sub-sections in the standard names list

You can see these changes in the form of a Google doc for better visualization here: https://docs.google.com/document/d/19ysUCWDhv53W8fQbElW7opr_1Pm7ck95QRUyKM_qy4E/edit?tab=t.0 

Note: with this update, we have 347 standard names that are fully compliant with the rules we have set out. A big portion of the remainder are "flag"-type variables, indices, etc, which are not fully accounted for in the rules yet.

2024-12-13 23:27 UTC, climbfuji commented on standard_names.xml
> +      <standard_name name="coefficient"
Duplicate of line 26-29

2024-12-13 23:27 UTC, climbfuji commented on standard_names.xml
> +                     long_name="Ozone, O₃">
Will these non-ASCII characters work? (also line 246)

2024-12-13 23:27 UTC, climbfuji commented on standard_names.xml
> +      <standard_name name="upward_flux_of_water_vapor_mixing_ratio_wrt_moist_air_at_surface_for_mellor_yamada_janjic_surface_layer_scheme"
We should probably define MYJ as the abbreviation to use in the standard name, and the full name in the long name? Like PBL and GWD in my open PR?

2024-12-13 23:27 UTC, climbfuji commented on standard_names.xml
> +      <standard_name name="water_vapor_mixing_ratio_wrt_moist_air_at_surface_for_myj_schemes"
Here, MYJ should be uppercase in the standard name, and spelled out in the long name

2024-12-13 23:27 UTC, climbfuji commented on standard_names.xml
> +      <standard_name name="upward_latent_heat_flux_at_surface_from_coupled_process">
What is the difference between `for_coupling` and `from_coupled_process` (not for vs from, but coupling vs coupled process)?

2024-12-25 19:04 UTC, gold2718 commented on standard_names.xml
> +      <standard_name name="water_vapor_mixing_ratio_wrt_moist_air_at_surface_for_myj_schemes"
Rule 17 says names are insensitive, does it matter here?
If so, maybe we should add something and uppercase the abbreviations in the [Acronyms, Abbreviations, and Aliases](https://github.com/ESCOMP/CCPPStandardNames/blob/main/StandardNamesRules.rst#acronyms-abbreviations-and-aliases) section? Or is it just for initials of names?

2024-12-26 17:27 UTC, climbfuji commented on standard_names.xml
> +      <standard_name name="water_vapor_mixing_ratio_wrt_moist_air_at_surface_for_myj_schemes"
That (rule 17) is a good point I completely forgot about. I like consistency and would prefer either lowercase or uppercase. We can talk about it at one of the next meetings, if the majority thinks that case insensitive is fine, then I can live with that, too.

2025-01-01 17:13 UTC, gold2718 requested changes
Great (and great big) piece of work!
A few requested changes and a lot of questions along with a few suggestions.
Also, should all long names begin with an capitalized word? Right now, there is a mix.

2025-01-01 17:13 UTC, gold2718 commented on standard_names.xml
> +      <standard_name name="cumulative_downwelling_diffuse_uv_and_vis_shortwave_flux_at_surface_for_coupling_multiplied_by_timestep">
I think it would be helpful to spell out `uv_and_vis_shortwave` in a long name:
```suggestion
      <standard_name name="cumulative_downwelling_diffuse_uv_and_vis_shortwave_flux_at_surface_for_coupling_multiplied_by_timestep"
      long_name="Cumulative downwelling diffuse ultraviolet_and_visible parts of the shortwave flux at surface for coupling multiplied by timestep">
```
This suggestion also applies to other uses of `uv_and_vis_shortwave`.

2025-01-29 17:19 UTC, mkavulich commented on standard_names.xml
> +                     long_name="Ozone, O₃">
`long_name` should be able to handle any unicode characters since it is not used in any FORTRAN code context. Even if long names were eventually used in comments or even character variables, that would be fine according to the [FORTRAN 90 standard](https://wg5-fortran.org/N001-N1100/N692.pdf)*, so long as it's a character set supported by the OS. I think anything in UTF-32 should be allowed for long names, since Python can handle those characters and it's essentially universally supported among OS's. 

This does bring up the fact that we haven't defined a character set for the standard names; I'll add that to the to-do list. So long as we make anything that may possibly be used as a fortran variable/subroutine/other code strictly within the allowed Fortran character set, we should be good.

* The relevant section on page 18 is here:

>Additional characters may be representable in the processor, but may appear only in comments (3.3.1.1,
15 3.3.2.1), character constants (4.4.4), input/output records (9.1.1), and character string edit descriptors
16 (10.2.1).

2025-01-29 17:27 UTC, mkavulich commented on standard_names.xml
> +      <standard_name name="upward_flux_of_water_vapor_mixing_ratio_wrt_moist_air_at_surface_for_mellor_yamada_janjic_surface_layer_scheme"
I think this is a good idea, but I will add it to my next round of changes to avoid scope creep. There are probably more abbreviations to introduce beyond this, like MYNN.

2025-01-29 17:37 UTC, mkavulich commented on standard_names.xml
> +      <standard_name name="upward_latent_heat_flux_at_surface_from_coupled_process">
This is a good point: In general I think the use of "coupling" and "coupled" in variable names is ambiguous and problematic. Probably needs a deeper dive after this PR.

2025-01-29 18:30 UTC, mkavulich commented on standard_names.xml
> +                   long_name="Weight for specific humidity (water vapor mass mixing ratio with respect to moist air) at the top of the viscous sublayer">
It looks like "weight" is used to mean "weighting factor" in all current contexts. I'm not sure if referencing physical "weight" would ever be useful in standard names, but maybe it's worthy of discussion?

2025-01-29 18:32 UTC, mkavulich commented on standard_names.xml
> +      <standard_name name="nir_albedo_strong_cosz"
Yes, I'll add it to the list for next time since I have collected a bunch of acronyms to add

2025-01-29 20:51 UTC, mkavulich commented on standard_names.xml
> +                   long_name="Tendency of specific humidity (water vapor mass mixing ratio with respect to moist air) due to nonphysics">
It looks like this was one of the original standard names, so this was before my time. My impression is that this would refer to all non-physics processes, including the dycore and any other potential sources/sinks

2025-01-29 20:53 UTC, mkavulich commented on standard_names.xml
> +                     long_name="absolute_vorticity">
My intention is to include long names for all the variables in this section, but I hadn't gotten around to it for this round of commits. I can remove them for now if it's a big deal but I just wanted to note this is not intended to be the "final" version.

2025-01-29 20:58 UTC, mkavulich commented on standard_names.xml
> +        <type units="kg m-2">real</type>
These units were carried over as-is from a table that is in [https://github.com/ESCOMP/CCPPStandardNames/blob/release/v1/StandardNamesRules.rst#generic-names](StandardNamesRules.rst) (not yet removed). I do agree that if these base names are only intended to be components of other standard names then they do not necessarily need units, but on the other hand it is useful for many of these to specifically designate the units/dimensionality of the variable. So I could go either way on this, maybe calls for further discussion.

2025-01-29 21:11 UTC, mkavulich reviewed
@gold2718 @climbfuji Thanks for your thorough reviews. I've addressed most of your comments/suggestions, and those that I haven't I replied with a follow-up comment or question. Let me know if anything else needs resolving.

2025-01-29 21:11 UTC, mkavulich commented on StandardNamesRules.rst
> +   the variable in question is a substance or other quantity contained within some other the medium
Fixed

2025-01-29 21:11 UTC, mkavulich commented on StandardNamesRules.rst
> +| longwave               | Longwave radiation. Defined as thermal emission of EM radiation from the planet.    |
Done

2025-01-29 21:11 UTC, mkavulich commented on StandardNamesRules.rst
> +| shortwave              | Shortwave radiation. Defined as EM emissions from the sun                           |
Done

2025-01-29 21:11 UTC, mkavulich commented on standard_names.xml
> +      <standard_name name="coefficient"
Removed

2025-01-29 21:11 UTC, mkavulich commented on standard_names.xml
> +      </standard_name>
Fixed, not sure how that snuck in there

2025-01-29 21:11 UTC, mkavulich commented on standard_names.xml
> +      <standard_name name="cumulative_downwelling_diffuse_uv_and_vis_shortwave_flux_at_surface_for_coupling_multiplied_by_timestep">
Done

2025-01-29 21:11 UTC, mkavulich commented on standard_names.xml
> +      <standard_name name="cumulative_downwelling_direct_nir_shortwave_flux_at_surface_for_coupling_multiplied_by_timestep">
Done

2025-02-10 02:54 UTC, nusbaume approved these changes
Great work @mkavulich!  I had a couple of change requests, but nothing that requires a full re-review.

2025-02-10 02:54 UTC, nusbaume commented on standard_names.xml
> +      <standard_name name="exner_function_at_surface_adjacent_layer"
I believe this should be `wrt`, not `at` (as we are specifying what `p0` is, not just the value of the exner function at a given verical level):

```suggestion
      <standard_name name="exner_function_wrt_surface_adjacent_layer_pressure"
```

2025-02-10 02:54 UTC, nusbaume commented on standard_names.xml
> +                   long_name="exner function (p/p0)^(Rd/cp), where p0 is the pressure at vertical layer interfaces">
I believe this long name should be changed slightly to:

```suggestion
                   long_name="exner function (p/p0)^(Rd/cp), where p is the pressure at vertical layer interfaces">
```

2025-02-10 14:11 UTC, climbfuji commented on standard_names.xml
> +                     long_name="Ozone, O₃">
Can we talk about this at the next standard names meeting, please? My immediate reaction is to stick with the basic ASCII characters and nothing else, but maybe I can be convinced otherwise ;-) At the very least, we need to run a test with CCPP (SCM, UFS, ...) if the parsers (prebuild and capgen) can handle those characters.

2025-02-10 14:11 UTC, climbfuji commented on standard_names.xml
> +      <standard_name name="upward_latent_heat_flux_at_surface_from_coupled_process">
ok

2025-02-10 17:36 UTC, mkavulich commented on standard_names.xml
> +      <standard_name name="exner_function_at_surface_adjacent_layer"
From browsing the UFS code, this variable is specifically being used for the exner function at the surface adjacent layer, with respect to surface pressure. So I believe the existing name is correct.

Reference, for example: https://github.com/NCAR/ccpp-physics/blob/main/physics/SFC_Models/Land/Noahmp/noahmpdrv.F90#L546

2025-02-10 17:48 UTC, mkavulich commented on standard_names.xml
> +                   long_name="exner function (p/p0)^(Rd/cp), where p0 is the pressure at vertical layer interfaces">
Same here, `p0` is still the surface pressure, it's `p` that's at interfaces. P0 is defined as 1000 hPa in [GFS_rrtmg_pre.F90](https://github.com/NCAR/ccpp-physics/blob/main/physics/Interstitials/UFS_SCM_NEPTUNE/GFS_rrtmg_pre.F90#L387)

It could probably be re-worded to be more clear in this case, what do you think about this suggestion:

> Exner function (p/p0)^(Rd/cp) at vertical layer interfaces, where p0 is 1000 hPa

2025-02-10 22:24 UTC, nusbaume commented on standard_names.xml
> +                   long_name="exner function (p/p0)^(Rd/cp), where p0 is the pressure at vertical layer interfaces">
Hi @mkavulich, I think I am slightly confused by your response here?  I guess I was assuming that that if this variable is defined on the interfaces, then the only quantity that will actually vary on the interfaces is just the air pressure (`p`), and thus the update to the long_name would make that clear.  Maybe that's not the case though?

2025-02-10 22:27 UTC, nusbaume commented on standard_names.xml
> +      <standard_name name="exner_function_at_surface_adjacent_layer"
Hi again, I realized I misunderstood the code you were pointing me to.  My bad!  I think in this case the `standard_name` is correct (assuming it's using a globally constant `p0` value), but the `long_name` should be updated to the following:

`exner function (p/p0)^(Rd/cp), where p is the pressure at the surface adjacent layer`

Otherwise I think the long name implies that p0 varies in time and space, which it sounds like is not the case.

2025-02-13 16:47 UTC, mkavulich commented on standard_names.xml
> +                   long_name="exner function, (p/p0)^(Rd/cp)">
Clarify that this is vs constant p0 and the other is variable surface pressure

2025-02-13 16:48 UTC, mkavulich commented on standard_names.xml
> +                   long_name="exner function (p/p0)^(Rd/cp), where p0 is the pressure at the surface adjacent layer">
Include correct P0s here

2025-02-20 16:41 UTC, mkavulich commented on standard_names.xml
> +                     long_name="Ozone, O₃">
From today's discussion, we will restrict standard names (including long names) to ASCII character set.

2025-02-20 16:59 UTC, mkavulich commented on standard_names.xml
> +      <standard_name name="upward_latent_heat_flux_at_surface_from_coupled_process">
We will use "for coupling" suffix, and include a detailed description of what that means (pending further potential discussion)

2025-02-20 17:15 UTC, mkavulich commented on standard_names.xml
> +      <standard_name name="water_vapor_mixing_ratio_wrt_moist_air_at_surface_for_myj_schemes"
We will endorse the "case insensitivity" rule.

2025-02-20 17:23 UTC, mkavulich commented on standard_names.xml
> +        <type units="kg m-2">real</type>
Clarify that these are "preferred units" that indicate dimensionality and should be used if possible to avoid conversion overhead. Will include these in all sections (with "1" if units don't make sense)

2025-02-20 17:28 UTC, mkavulich commented on standard_names.xml
> +                   long_name="Weight for specific humidity (water vapor mass mixing ratio with respect to moist air) at the top of the viscous sublayer">
We discussed at today's meeting that "weight" is a synonym for "scaling factor" in all existing uses, so we will convert these to "scaling factor".

2025-02-27 14:16 UTC, gold2718 commented on tools/write_standard_name_table.py
> +                continue
It doesn't look too indenty to me but I don't think there is a standard here (even Linus breaks his "... if you need more than 3 levels of indentation, you're screwed anyway, and should fix your program." rule).

2025-02-27 14:55 UTC, gold2718 requested changes
This looks better but not all the issues are resolved (e.g., `vis` to `visible`), at least as of cd5ba374b7b8e0f106783eab93f31bae7479978a.

2025-02-27 14:55 UTC, gold2718 commented on standard_names.xml
> +      <standard_name name="diffuse_visible_albedo"
Is this one getting changed to `vis`?

2025-02-27 14:55 UTC, gold2718 commented on standard_names.xml
> +      <standard_name name="direct_visible_albedo"
These don't seem to have been changed.

2025-02-27 14:55 UTC, gold2718 commented on standard_names.xml
> +                   long_name="Tendency of specific humidity (water vapor mass mixing ratio with respect to moist air) due to nonphysics">
To me, this feels very imprecise and not very much in the spirit of all the exacting language we have been working on. This is more to the community but could this be spelled out in the name by separating sources/sinks? `dycore` is a pretty different source than `emission`.

2025-02-27 15:58 UTC, mkavulich commented on standard_names.xml
> +      <standard_name name="direct_visible_albedo"
@gold2718 Since this is a multi-round effort I am trying not to snowball additional disparate changes into this PR; I have noted this as a "to-do" for the next branch. Sorry I wasn't more clear in my initial reply.

2025-02-27 16:02 UTC, mkavulich commented on standard_names.xml
> +      <standard_name name="direct_visible_albedo"
Since this wasn't all that big of a change, I went ahead and applied it here.

2025-02-27 16:05 UTC, mkavulich commented on standard_names.xml
> +                   long_name="Tendency of specific humidity (water vapor mass mixing ratio with respect to moist air) due to nonphysics">
I think this needs further discussion/investigation since this is an existing long-standing name;  would it be all right if we pushed this to the next round of changes?

2025-02-27 22:10 UTC, gold2718 commented on standard_names.xml
> +      <standard_name name="direct_visible_albedo"
Thanks! What would help in these situations if there were one or more issues open with the "to-do" list so I could cross-check before complaining.

2025-02-27 22:21 UTC, gold2718 commented on standard_names.xml
> +                   long_name="Tendency of specific humidity (water vapor mass mixing ratio with respect to moist air) due to nonphysics">
Sure, see #90.

2025-02-27 22:23 UTC, gold2718 commented
Will #86 be merged in before final review?

2025-03-03 22:46 UTC, mkavulich commented
@gold2718 I did not plan to resolve conflicts between the main branch and release branch at this time, since the changes are already so divergent. But this is a good idea; I will make a follow-up PR right now to bring in the relevant changes since this branch was cut.

I thought I had responded to your latest comments but I guess I forgot; I made the changes you requested re: vis to visible, was there anything else that needed attention or are you okay with this being merged?

2025-03-03 22:53 UTC, svahl991 commented
This PR changes many of the names that we just adapted in JEDI last fall during a code sprint that took considerable effort. Before merging this, can we create a tag or version of this repository that JEDI can reference?

2025-03-04 12:07 UTC, gold2718 commented on standard_names.xml
> +                   long_name="Weight for specific humidity (water vapor mass mixing ratio with respect to moist air) at the top of the viscous sublayer">
Please open an issue describing this change.

2025-03-04 12:09 UTC, gold2718 commented
> @gold2718 @climbfuji Thanks for your thorough reviews. I've addressed most of your comments/suggestions, and those that I haven't I replied with a follow-up comment or question. Let me know if anything else needs resolving.

Please just open issues for any changes that need changing (based on comments on this PR) so that they are not lost. I do not see one for the `weight` to `scaling_factor` change.

2025-03-04 12:35 UTC, gold2718 commented
> This PR changes many of the names that we just adapted in JEDI last fall during a code sprint that took considerable effort. Before merging this, can we create a tag or version of this repository that JEDI can reference?

No objections here. `v0.1.2`?

2025-03-04 15:49 UTC, mkavulich commented
> This PR changes many of the names that we just adapted in JEDI last fall during a code sprint that took considerable effort. Before merging this, can we create a tag or version of this repository that JEDI can reference?

@svahl991 Just a note, this PR is not being merged to `main`, but to a branch `release/v1` as part of a multi-stage effort to make the names and rules consistent. We will not be applying these changes to the main branch until there has been substantial input from all interested parties.

We had discussed creating a tag back in the fall for JEDI's "stable" version but last time we had that discussion there were still some changes being debated. Is the current state of main the preferred version to make this tag? Or would it be a previous hash?

2025-03-04 16:08 UTC, mkavulich commented
@gold2718 I have opened some issues that I think covers all of your concerns; I have been tracking them in a google doc but making sure they are tracked here as well is a good idea.

2025-03-04 16:56 UTC, svahl991 commented
> Just a note, this PR is not being merged to main, but to a branch release/v1 as part of a multi-stage effort to make the names and rules consistent.

Thanks @mkavulich . That's an important detail I missed. So, to make sure I understand:

1. The `main` branch is still the "official" ESM (formerly CCPP) name for the time being.
2. The `release/v1` branch is building up a major re-work of the rules and names, but is not yet "official".
3. The plan is to build this re-work up in the `release` branch, get consensus, and merge it into `main` at some point in the future.

I apologize if I missed and/or forgot past communications about this.

2025-03-04 17:13 UTC, gold2718 approved these changes
All looks good now, thanks!
(and thanks to @mkavulich for getting all those issues open)

2025-03-04 18:36 UTC, svahl991 commented on Metadata-standard-names.md
> +* `water_vapor_mixing_ratio_wrt_moist_air_at_2m`: Specific humidity (water vapor mass mixing ratio with respect to moist air) at two meters above surface
We have found in our work on JEDI that the term "specific humidity" does not have an internationally agreed-upon meaning. I suggest not using it at all to avoid confusion. Or, if it must be used, to qualify it. (When the UKMO uses the term "specific humidity" they mean `water_vapor_mixing_ratio_wrt_moist_air_and_condensed_water`, which is two lines below this one.)

2025-03-04 19:07 UTC, mkavulich commented
@svahl991 Your understanding is correct. This re-factor is part of a lead-up to standing up a more formal governance outside of the CCPP framework's purview; we don't yet have anything official but I have been putting out feelers to ensure that all interested groups are represented. As an active contributor from JCSDA, I'll certainly be sure you're in the loop when we start scheduling meetings.

With regards to specific humidity, you'll note that this PR removes `specific_humidity` from all standard names, exactly because of the problems you mentioned (conflicting/non-standardized definitions), see [here](https://github.com/ESCOMP/ESMStandardNames/pull/87/files#diff-bb599d1972097b4e19b15ce1f799e76cf32576a4281e742ddd07ff578978482bL1719) for example. But because it is a common term, we decided it should stay in long_name entries where relevant, with a parenthetical qualifier of the exact definition as you see here. I could see where it might still be an issue though, so I will open an issue where we can discuss this in more detail.

2025-03-04 19:16 UTC, merged